# Use this secret as a template to patch existing secret in ingress-system namespace and also make sure the name of this secret is default-certificate or whichever is present and used by ingress.
# - After that it is better to bounce ingress pod and tp-tunnel pods to make sure they pick up the new certificate.

apiVersion: v1
data:
  tls.crt: 
  tls.key: 
kind: Secret
metadata:
  name: default-certificate
  namespace: ingress-system
type: Opaque
